name: Environment Deployment

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose an environment
        options:
          - "DEV"
          - "QA-Internal"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to selected environment
        run: |
          environment="${{ github.event.inputs.environment }}"
          echo "Deploying to $environment environment..."
          
